apiVersion: apps/v1
kind: Deployment
metadata:
  name: cine-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cine-app
  template:
    metadata:
      labels:
        app: cine-app
    spec:
      containers:
        - name: cine-app
          image: mnifla/cine-app:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"  # 100 milicores de CPU (equivalente al 10% de un núcleo)
              memory: "128Mi"  # 128 MB de memoria
            limits:
              cpu: "500m"  # 500 milicores de CPU (equivalente al 50% de un núcleo)
              memory: "512Mi"  # 512 MB de memoria

